### ISSUE TITLE
Serializers - Paw - Rename "JSON Schema Faker"

### ISSUE THREAD

**Issue by mittsh** [luckymarmot/API-Flow#64]
![image](https://cloud.githubusercontent.com/assets/1319906/17848207/723307ce-6852-11e6-8f48-5e4703083cac.png)

It seems to me like a confusing name for users who haven't heard about JSF yet. Maybe somehting like "Use value randomizers for environment variables" etc.

**Comment by JonathanMontane** [comment]
renamed to `randomizers`
